######################################################################
# Automatically generated by qmake (2.01a) ? 12? 1 21:48:38 2010
######################################################################

CXX = g++
VERSION = 0.1
TEMPLATE = app
TARGET = kepwing
QT +=
DEPENDPATH += . src
LIBS += -leb
QMAKE_CXXFLAGS += -ggdb
INCLUDEPATH += .
CONFIG += release link_pkgconfig
PKGCONFIG += libxdg-basedir 

# Input

HEADERS += src/*h
SOURCES += src/*cpp







